blog/api/urls.py
from django.urls import path
from blog.api.views import (
    registration_view,
    account_properties_view,
    update_account_view
)
from rest_framework.authtoken.views import obtain_auth_token
app_name = 'blog'

urlpatterns = [
    path('properties', account_properties_view, name='properties'),
    path('properties/update', update_account_view, name='update'),
    path('register', registration_view, name='register'),
    path('login', obtain_auth_token, name='login'),
]

blog/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.home, name='home'),
    path('mapssas/',views.buymaps,name='buymaps'),
    path('account/', views.account_view, name='account'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile_view, name='profile'),
    # path('edit/', views.edit_profile_view, name='edit'),
    path('search/', views.search_view, name='search'),
    path('rent/', views.rent_view, name='rent'),
    path('sell/', views.sell_view, name='sell'),
    path('type1/', views.type1_view, name='type1'),
    path('type2/', views.type2_view, name='type2'),
    path('search_s/', views.sell_search_view, name='search_s'),
    path('search_r/', views.rent_search_view, name='search_r'),
    path('search_t1/', views.t1_search_view, name='search_t1'),
    path('search_t2/', views.t2_search_view, name='search_t2'),
    path('<city>/', views.city_view, name='city'),
    path('<city>/list', views.city_props, name='props'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         views.activate, name='activate'),
    path('profile/', views.profile_view, name='profile')      
]

mysite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from blog.views import (
    must_authenticate_view
)

urlpatterns = [
    path('property/', include('property.urls')),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('must_authenticate/', must_authenticate_view,
         name="must_authenticate"),

    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payments/', include('payments.urls')),
    # rest_framework
    path('api/property/', include('property.api.urls', 'property_api')),
    path('api/account/', include('blog.api.urls', 'blog_api'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

property/urls.py
from django.urls import path
from property.views import(
    create_property_view,
    detail_property_view,
    edit_property_view,
    check_price,
    bank_api
)

app_name = 'property'

urlpatterns = [
    path('create/', create_property_view, name="create"),
    path('<slug>/', detail_property_view, name="detail"),
    path('<slug>/price', check_price, name="price"),
    path('<slug>/edit', edit_property_view, name="edit"),
    path('<slug>/bank', bank_api, name="bank"),

]

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from blog.models import UserProfile


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', ]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image', ]


def save(self, commit=True):
    user_details = self.instance
    user_details.first_name = self.cleaned_data['first_name']
    user_details.last_name = self.cleaned_data['last_name']
    user_details.email = self.cleaned_data['email']
    user_details.user_phone = self.cleaned_data['user_phone']
    user_details.user_address = self.cleaned_data['user_address']
    user_details.user_city = self.cleaned_data['user_city']
    user_details.user_zipcode = self.cleaned_data['user_zipcode']

    # if self.cleaned_data['image']:
    #     property_listings.image = self.cleaned_data['image']

    if commit:
        user_details.save()
        return user_details

blog/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated

from blog.api.serializers import RegistrationSerializer, AccountPropertiesSerializer
from rest_framework.authtoken.models import Token


@api_view(['POST', ])
def registration_view(request):

    serializer = RegistrationSerializer(data=request.data)
    data = {}
    if serializer.is_valid():
        account = serializer.save()
        data['response'] = 'successful'
        data['email'] = account.email
        data['username'] = account.username
        token = Token.objects.get(user=account).key
        data['token'] = token
    else:
        data = serializer.errors
    return Response(data)


@api_view(['GET', ])
@permission_classes((IsAuthenticated,))
def account_properties_view(request):
    try:
        account = request.user
    except Account.DoesNotExist:
        return Response(status=HTTP_404_NOT_FOUND)

    serializer = AccountPropertiesSerializer(account)
    return Response(serializer.data)


@api_view(['PUT', ])
@permission_classes((IsAuthenticated,))
def update_account_view(request):
    try:
        account = request.user
    except Account.DoesNotExist:
        return Response(status=HTTP_404_NOT_FOUND)

    serializer = AccountPropertiesSerializer(account, data=request.data)
    data = {}
    if serializer.is_valid():
        serializer.save()
        data['response'] = "Account update success"
        return Response(data=data)

    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse, HttpResponseRedirect, HttpResponse,  get_object_or_404
from django.contrib.auth import login, authenticate, logout
from .forms import SignupForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required
from property.models import PropertyListing

from blog.models import UserProfile
from .choices import type_choices, price_choices
from django.db.models import Q
import json
from .forms import UserUpdateForm

def home(request):
    context = {}
    if request.user.is_authenticated:
        property_listings_r = PropertyListing.objects.filter(
            Q(types='R') | Q(types='B')).exclude(owner=request.user)
        property_listings_s = PropertyListing.objects.filter(
            Q(types='S') | Q(types='B')).exclude(owner=request.user)
        lati = PropertyListing.objects.all().values_list('latitude').exclude(owner=request.user)
        longi = PropertyListing.objects.all().values_list('longitude').exclude(owner=request.user)
        slug = PropertyListing.objects.all().values_list('slug').exclude(owner=request.user)
    else:
        property_listings_r = PropertyListing.objects.filter(
            Q(types='R') | Q(types='B'))
        property_listings_s = PropertyListing.objects.filter(
            Q(types='S') | Q(types='B'))
        lati = PropertyListing.objects.all().values_list('latitude')
        longi = PropertyListing.objects.all().values_list('longitude')
        slug = PropertyListing.objects.all().values_list('slug')
    cities = PropertyListing.objects.all().values_list('city', flat=True).distinct()

    lat= []
    lon = []
    slugs = []
    for i in lati:
        lat +=[i[0]]
    for i in longi:
        lon +=[i[0]]
    for i in slug:
        slugs+=[i[0]]
    context = {"property_listings_r": property_listings_r, "property_listings_s": property_listings_s,
               "cities": cities, "type_choices":type_choices, "price_choices":price_choices,
               "lat":lat, "lon":lon, "slug":slugs, "values":request.GET}
    return render(request, 'home.html', context)


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            message = render_to_string('acc_active_email.html', {
                'user': user, 'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            # Sending activation link in terminal
            # user.email_user(subject, message)
            mail_subject = 'Activate your blog account.'
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration.')
            # return render(request, 'acc_active_sent.html')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})
def buymaps(request):
    return render(request,'buymaps.html')

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('blog:home'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login but failed!")
            print("Username: {} and password {}".format(username, password))
            return render(request, 'login.html', {'msg': 'Invalid Details Provided!'})
    else:
        return render(request, 'login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog:home'))


def account_view(request):
    if not request.user.is_authenticated:
        return redirect("blog:login")
    context = {}
    property_listings = PropertyListing.objects.filter(owner=request.user)
    context['property_listings'] = property_listings
    return render(request, "account.html", context)




def profile_view(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
       
        if u_form.is_valid():
            u_form.save()
           
            messages.success(request, f'Your account has been updated!')
            return redirect('http://127.0.0.1:8000/profile/')

    else:
        u_form = UserUpdateForm(instance=request.user)
       

    context = {
        'u_form': u_form,
       
    }

    return render(request, 'profile.html', context)

# def edit_profile_view(request):
#     context = {}
#     user = request.user
#     if not user.is_authenticated:
#         return redirect("must_authenticate")
#     user_details = UserProfile.objects.filter(user=request.user)
#     if request.POST:
#         form = UpdateProfileForm(
#             request.POST or None, request.FILES or None, instance=user_details)
#         if form.is_valid():
#             obj = form.save(commit=False)
#             obj.save()
#             context['success_message'] = "Updated"
#             user_details = obj
#     form = UpdateProfileForm(
#         initial={
#             "first_name": user_details.first_name,
#             "last_name": user_details.last_name,
#         }
#     )
#     context['form'] = form
#     return render(request, 'blog/edit_profile.html', context)


def search_view(request):
    if request.user.is_authenticated:
        search_listing = PropertyListing.objects.all().exclude(owner=request.user)
    else:
        search_listing = PropertyListing.objects.all()

    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            search_listing = search_listing.filter(city__iexact = city)

    if 'type' in request.GET:
        type = request.GET['type']
        if type:
            search_listing = search_listing.filter(types__iexact = type)

    if 'minprice' in request.GET:
        minprice = request.GET['minprice']
        if minprice:
            search_listing = search_listing.filter(price__gte = minprice)

    if 'maxprice' in request.GET:
        maxprice = request.GET['maxprice']
        if maxprice:
            search_listing = search_listing.filter(price__lte = maxprice)

    context = {"search_listing": search_listing}
    return render(request, "search.html", context)


def sell_search_view(request):
    if request.user.is_authenticated:
        search_listing = PropertyListing.objects.filter(Q(types='S') | Q(types='B')).exclude(owner=request.user)
    else:
        search_listing = PropertyListing.objects.filter(Q(types='S') | Q(types='B'))

    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            search_listing = search_listing.filter(city__iexact = city)

    if 'minprice' in request.GET:
        minprice = request.GET['minprice']
        if minprice:
            search_listing = search_listing.filter(price__gte = minprice)

    if 'maxprice' in request.GET:
        maxprice = request.GET['maxprice']
        if maxprice:
            search_listing = search_listing.filter(price__lte = maxprice)

    context = {"search_listing": search_listing}
    return render(request, "search.html", context)


def rent_search_view(request):
    if request.user.is_authenticated:
        search_listing = PropertyListing.objects.filter(Q(types='R') | Q(types='B')).exclude(owner=request.user)
    else:
        search_listing = PropertyListing.objects.filter(Q(types='R') | Q(types='B'))

    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            search_listing = search_listing.filter(city__iexact = city)

    if 'minprice' in request.GET:
        minprice = request.GET['minprice']
        if minprice:
            search_listing = search_listing.filter(price__gte = minprice)

    if 'maxprice' in request.GET:
        maxprice = request.GET['maxprice']
        if maxprice:
            search_listing = search_listing.filter(price__lte = maxprice)

    context = {"search_listing": search_listing}
    return render(request, "search.html", context)


def t1_search_view(request):
    if request.user.is_authenticated:
        search_listing = PropertyListing.objects.filter(stay='H').exclude(owner=request.user)
    else:
        search_listing = PropertyListing.objects.filter(stay='H')

    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            search_listing = search_listing.filter(city__iexact = city)

    if 'type' in request.GET:
        type = request.GET['type']
        if type:

blog/templates/acc_active_email.html
{% autoescape off %} Hi {{ user.username }}, Please click on the link to confirm
your registration, http://{{ domain }}{% url 'blog:activate' uidb64=uid token=token
%} {% endautoescape %}

<!-- {% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'blog:activate' uidb64=uid token=token %}
{% endautoescape %} -->

blog/templates/acc_active_sent.html
{% extends 'base.html' %}

{% block content %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

blog/templates/account.html
{% extends 'base.html' %}
{% block body %}

<section class="pager-sec bfr">
  <div class="container">
    <div class="pager-sec-details">
      <h3>My account</h3>

      <ul>
        <li><a href="#" title="">Home</a></li>
        <li><span>My account</span></li>
      </ul>
    </div>
    <!--pager-sec-details end-->
  </div>
</section>

<section class="blog-grid section-padding">

  {% if property_listings %}

  <div class="container">
    <div class="blog-grid-posts">
      <div class="row">

        {% for property_listings in property_listings %}

        <div class="col-lg-4 col-md-6 col-sm-6 col-12">
          <div class="blog-single-post">
            <div class="blog-img">
              <a href="{% url 'property:detail' property_listings.slug %}" title="">
                <img src="{{ property_listings.image.url }}" alt="">
              </a>
              <div class="view-post">
                <a href="{% url 'property:detail' property_listings.slug %}" title="" class="view-posts">View Post</a>
              </div>
            </div>
            <!--blog-img end-->
            <div class="post_info">
              <ul class="post-nfo">
                <li><i class="la la-calendar"></i>{{ property_listings.date_updated }}
                </li>
              </ul>
              <h3><a href="{% url 'property:detail' property_listings.slug %}"
                  title="">{{ property_listings.title }}</a></h3>
              <p>{{ property_listings.body | safe }}</p>
              <span>{{ property_listings.Verify }}</span>
              <a href="{% url 'property:detail' property_listings.slug %}" title="">Read More <i
                  class="la la-long-arrow-right"></i></a>
            </div>
            <a href="{% url 'property:detail' property_listings.slug %}" title="" class="ext-link"></a>
          </div>
          <!--blog-single-post end-->
        </div>

        {% endfor %}


      </div>
    </div>
    <!--blog-grid-posts end-->
  </div>

  {% else %}
  <div class="container">
    <h1>
      You have no blog posts. Create a post
      <a href="{% url 'property:create' %}">here</a>.
    </h1>
  </div>


  {% endif %}

</section>

{% endblock %}

blog/templates/login.html
{% extends 'base.html' %} {% block body %}

<div>
  <h3 class="text-center my-3">Sign In to your Account</h3>
  <form method="POST" class="mx-auto w-25">
    {% csrf_token %}
    <div class="form-field">
      <input type="text" name="username" placeholder="Username">
    </div>
    <div class="form-field">
      <input type="password" name="password" placeholder="Password">
    </div>
    <div class="form-cp">
      <div class="form-field">
        <div class="input-field">
          <input type="checkbox" name="ccc" id="cc1">
          <label for="cc1">
            <span></span>
            <small>Remember me</small>
          </label>
        </div>
      </div>
      <a href="#" title="">Forgot Password?</a>
    </div>
    <!--form-cp end-->
    <button type="submit" class="btn2">Sign In</button>
  </form>
</div>
<br>


{% endblock %}

blog/templates/must_authenticate.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="d-flex flex-column">
    <p class="m-auto">Must authenticate to view</p>
    <p class="m-auto">
      <a href="{% url 'blog:signup' %}">Register</a>
    </p>
  </div>
</div>

{% endblock content %}

blog/templates/rent.html
{% extends 'base.html' %}
{% block body %}

<section class="form_sec">
            <h3 class="vis-hid">Invisible</h3>
            <div class="container">
              <form action="{% url 'blog:search_r' %}" class="row banner-search">
                  <div class="form_field addres">
                      <input type="text" class="form-control" placeholder="Enter City" name='city'>
                  </div>

                  <div class="form_field tpmax">
                      <div class="form-group">
                        <label class="sr-only">Min-Price</label>
                          <select name="minprice" class="form-control">
                            <option selected="true" disabled="disabled">Min-Price
                            <i class="fa fa-angle-down"></i></option>
                            {% for key,value in price_choices.items %}
                              <option value="{{key}}">{{value}}</option>
                            {% endfor %}
                          </select>
                      </div>
                  </div>
                  <div class="form_field tpmax">
                      <div class="form-group">
                        <label class="sr-only">Max-Price</label>
                          <select name="maxprice" class="form-control">
                            <option selected="true" disabled="disabled">Max-Price
                            <i class="fa fa-angle-down"></i></option>
                            {% for key,value in price_choices.items %}
                              <option value="{{key}}">{{value}}</option>
                            {% endfor %}
                          </select>
                      </div>
                  </div>
                  <div class="form_field srch-btn">
                        <button class="btn btn-outline-primary ">
                            <i class="la la-search"></i>

                    </div>
              </form>
            </div>
        </section><!--form_sec end-->

<section class="blog-grid section-padding">

  {% if property_listings_r1 %}

  <div class="container">
    <div class="blog-grid-posts">
      <div class="row">

        {% for property_listings in property_listings_r1 %}

        <div class="col-lg-4 col-md-6 col-sm-6 col-12">
          <div class="blog-single-post">
            <div class="blog-img">
              <a href="{% url 'property:detail' property_listings.slug %}" title="">
                <img src="{{ property_listings.image.url }}" alt="">
                <div class="rate-info">
                    <font color="white">₹ {{ property_listings.price }}
                    <span>per month</span></font>
                </div>
              </a>
              <div class="view-post">
                <a href="{% url 'property:detail' property_listings.slug %}" title="" class="view-posts">View Post</a>
              </div>
            </div>
            <!--blog-img end-->
            <div class="post_info">
              <ul class="post-nfo">
                <li><i class="la la-calendar"></i>{{ property_listings.date_updated }} for {{ property_listings.types }}
                  by {{ property_listings.owner }}
                </li>
              </ul>
              <h3><a href="{% url 'property:detail' property_listings.slug %}"
                  title="">{{ property_listings.title }}</a></h3>
                  <i class="la la-map-marker"></i>{{ property_listings.city }},{{ property_listings.state }}<br><br>
              <p>{{ property_listings.body | safe }}</p>
              <a href="{% url 'property:detail' property_listings.slug %}" title="">Read More <i
                  class="la la-long-arrow-right"></i></a>
            </div>
            <a href="{% url 'property:detail' property_listings.slug %}" title="" class="ext-link"></a>
          </div>
          <!--blog-single-post end-->
        </div>

        {% endfor %}


      </div>
    </div>
    <!--blog-grid-posts end-->
  </div>



  {% endif %}

</section>

{% endblock %}
{% block map %}
<h1 style="font-size:25px;margin-left:94px">Our homes around the World</h1>
<div id="map_div" style="width:90%;height:500px;margin: 90px;"></div>
<script>
// var points = [
//   ['name1', 59.9362384705039, 30.19232525792222, 12, 'https://docs.jsfiddle.net/use-cases/code-snippets-hosting'],
//   ['name2', 59.941412822085645, 30.263564729357767, 11, 'https://jsfiddle.net/about'],
//   ['name3', 59.939177197629455, 30.273554411974955, 10, 'https://docs.jsfiddle.net/']
// ];
var lat= {{lat|safe}};
var long = {{lon|safe}};
var slug = {{slug|safe}}
var link = "http://127.0.0.1:8000/property/"
var name= ["name"];
var ind = 12;
// var url=['https://docs.jsfiddle.net/use-cases/code-snippets-hosting'];
function setMarkers(map,lat,long,name,ind,slug) {
  var shape = {
    coord: [1, 1, 1, 20, 18, 20, 18 , 1],
    type: 'poly'
  };

  for (var i = 0; i < lat.length; i++) {
    var myLatLng = new google.maps.LatLng(lat[i], long[i]);
    var marker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      shape: shape,
      title: name[i],
      zIndex: ind,
      url: link.concat(slug[i])
    });
    google.maps.event.addListener(marker, 'click', function() {
      window.location.href = this.url;
    });
  }
}

function initFunc() {
  var myOptions = {
    center: new google.maps.LatLng(13.5269, 79.9802),
    zoom: 9,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("map_div"),myOptions);
  setMarkers(map,lat,long,name,ind,slug);
}

</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYl3jkGGMzayse2hTeqApY0qanvqXdmaI&callback=initFunc">
</script>
{% endblock %}

blog/templates/sell.html
{% extends 'base.html' %}
{% block body %}

<section class="form_sec">
            <h3 class="vis-hid">Invisible</h3>
            <div class="container">
              <form action="{% url 'blog:search_s' %}" class="row banner-search">
                  <div class="form_field addres">
                      <input type="text" class="form-control" placeholder="Enter City" name='city'>
                  </div>

                  <div class="form_field tpmax">
                      <div class="form-group">
                        <label class="sr-only">Min-Price</label>
                          <select name="minprice" class="form-control">
                            <option selected="true" disabled="disabled">Min-Price
                            <i class="fa fa-angle-down"></i></option>
                            {% for key,value in price_choices.items %}
                              <option value="{{key}}">{{value}}</option>
                            {% endfor %}
                          </select>
                      </div>
                  </div>
                  <div class="form_field tpmax">
                      <div class="form-group">
                        <label class="sr-only">Max-Price</label>
                          <select name="maxprice" class="form-control">
                            <option selected="true" disabled="disabled">Max-Price
                            <i class="fa fa-angle-down"></i></option>
                            {% for key,value in price_choices.items %}
                              <option value="{{key}}">{{value}}</option>
                            {% endfor %}
                          </select>
                      </div>
                  </div>
                  <div class="form_field srch-btn">
                        <button class="btn btn-outline-primary ">
                            <i class="la la-search"></i>

                    </div>
              </form>
            </div>
        </section><!--form_sec end-->

<section class="blog-grid section-padding">

  {% if property_listings_s1 %}

  <div class="container">
    <div class="blog-grid-posts">
      <div class="row">

        {% for property_listings in property_listings_s1 %}

        <div class="col-lg-4 col-md-6 col-sm-6 col-12">
          <div class="blog-single-post">
            <div class="blog-img">
              <a href="{% url 'property:detail' property_listings.slug %}" title="">
                <img src="{{ property_listings.image.url }}" alt="">
                <div class="rate-info">
                    <font color="white">₹ {{ property_listings.price }}
                    </font>

                </div>
              </a>
              <div class="view-post">
                <a href="{% url 'property:detail' property_listings.slug %}" title="" class="view-posts">View Post</a>
              </div>
            </div>
            <!--blog-img end-->
            <div class="post_info">
              <ul class="post-nfo">
                <li><i class="la la-calendar"></i>{{ property_listings.date_updated }} for {{ property_listings.types }}
                  by {{ property_listings.owner }}
                </li>
              </ul>
              <h3><a href="{% url 'property:detail' property_listings.slug %}"
                  title="">{{ property_listings.title }}</a></h3>
                  <i class="la la-map-marker"></i>{{ property_listings.city }},{{ property_listings.state }}<br><br>
              <p>{{ property_listings.body | safe }}</p>
              <a href="{% url 'property:detail' property_listings.slug %}" title="">Read More <i
                  class="la la-long-arrow-right"></i></a>
            </div>
            <a href="{% url 'property:detail' property_listings.slug %}" title="" class="ext-link"></a>
          </div>
          <!--blog-single-post end-->
        </div>

        {% endfor %}


      </div>
    </div>
    <!--blog-grid-posts end-->
  </div>



  {% endif %}

</section>

{% endblock %}
{% block map %}
<h1 style="font-size:25px;margin-left:94px">Our homes around the World</h1>
<div id="map_div" style="width:90%;height:500px;margin: 90px;"></div>
<script>
// var points = [
//   ['name1', 59.9362384705039, 30.19232525792222, 12, 'https://docs.jsfiddle.net/use-cases/code-snippets-hosting'],
//   ['name2', 59.941412822085645, 30.263564729357767, 11, 'https://jsfiddle.net/about'],
//   ['name3', 59.939177197629455, 30.273554411974955, 10, 'https://docs.jsfiddle.net/']
// ];
var lat= {{lat|safe}};
var long = {{lon|safe}};
var slug = {{slug|safe}}
var link = "http://127.0.0.1:8000/property/"
var name= ["name"];
var ind = 12;
// var url=['https://docs.jsfiddle.net/use-cases/code-snippets-hosting'];
function setMarkers(map,lat,long,name,ind,slug) {
  var shape = {
    coord: [1, 1, 1, 20, 18, 20, 18 , 1],
    type: 'poly'
  };

  for (var i = 0; i < lat.length; i++) {
    var myLatLng = new google.maps.LatLng(lat[i], long[i]);
    var marker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      shape: shape,
      title: name[i],
      zIndex: ind,
      url: link.concat(slug[i])
    });
    google.maps.event.addListener(marker, 'click', function() {
      window.location.href = this.url;
    });
  }
}

function initFunc() {
  var myOptions = {
    center: new google.maps.LatLng(13.5269, 79.9802),
    zoom: 9,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("map_div"),myOptions);
  setMarkers(map,lat,long,name,ind,slug);
}

</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYl3jkGGMzayse2hTeqApY0qanvqXdmaI&callback=initFunc">
</script>
{% endblock %}