blog/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.home, name='home'),
    path('mapssas/',views.buymaps,name='buymaps'),
    path('account/', views.account_view, name='account'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile_view, name='profile'),
    # path('edit/', views.edit_profile_view, name='edit'),
    path('search/', views.search_view, name='search'),
    path('rent/', views.rent_view, name='rent'),
    path('sell/', views.sell_view, name='sell'),
    path('type1/', views.type1_view, name='type1'),
    path('type2/', views.type2_view, name='type2'),
    path('search_s/', views.sell_search_view, name='search_s'),
    path('search_r/', views.rent_search_view, name='search_r'),
    path('search_t1/', views.t1_search_view, name='search_t1'),
    path('search_t2/', views.t2_search_view, name='search_t2'),
    path('<city>/', views.city_view, name='city'),
    path('<city>/list', views.city_props, name='props'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         views.activate, name='activate'),
    path('profile/', views.profile_view, name='profile')      
]

mysite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from blog.views import (
    must_authenticate_view
)

urlpatterns = [
    path('property/', include('property.urls')),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('must_authenticate/', must_authenticate_view,
         name="must_authenticate"),

    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payments/', include('payments.urls')),
    # rest_framework
    path('api/property/', include('property.api.urls', 'property_api')),
    path('api/account/', include('blog.api.urls', 'blog_api'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

property/api/urls.py
from django.urls import path
from property.api.views import (
    api_detail_view,
    api_update_property_view,
    api_delete_property_view,
    api_create_property_view,
    ApiPropertyListView,
    ApiPropertyListView1,
    ApiBankListView,
    ApiAreaPriceView,
    followview

)

app_name = 'property'

urlpatterns = [

    path('create', api_create_property_view, name='create'),
    path('list', ApiPropertyListView.as_view(), name='list'),
    path('list_get', ApiPropertyListView1.as_view(), name='list_get'),
    path('list1/', followview.as_view(), name='list1'),
    path('area', ApiAreaPriceView.as_view(), name='area'),
    path('bank', ApiBankListView.as_view(), name='bank'),
    path('<slug>/', api_detail_view, name='detail'),
    path('<slug>/update', api_update_property_view, name='update'),
    path('<slug>/delete', api_delete_property_view, name='delete'),


]

property/urls.py
from django.urls import path
from property.views import(
    create_property_view,
    detail_property_view,
    edit_property_view,
    check_price,
    bank_api
)

app_name = 'property'

urlpatterns = [
    path('create/', create_property_view, name="create"),
    path('<slug>/', detail_property_view, name="detail"),
    path('<slug>/price', check_price, name="price"),
    path('<slug>/edit', edit_property_view, name="edit"),
    path('<slug>/bank', bank_api, name="bank"),

]

property/models.py
from django.db import models

from django.db.models.signals import pre_save, post_delete
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver


def upload_location(instance, filename):
    file_path = 'property/{owner_id}/{title}-{filename}'.format(
        owner_id=str(instance.owner.id), title=str(instance.title), filename=filename)
    return file_path


class PropertyListing(models.Model):

    title = models.CharField(max_length=50, null=False, blank=False)
    body = models.TextField(max_length=5000, null=False, blank=False)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    image2 = models.ImageField(
        upload_to=upload_location, null=True, blank=True)
    image3 = models.ImageField(
        upload_to=upload_location, null=True, blank=True)
    image4 = models.ImageField(
        upload_to=upload_location, null=True, blank=True)
    image5 = models.ImageField(
        upload_to=upload_location, null=True, blank=True)
    image6 = models.ImageField(
        upload_to=upload_location, null=True, blank=True)
    image7 = models.ImageField(
        upload_to=upload_location, null=True, blank=True)
    address = models.CharField(max_length=200, default=False)
    city = models.CharField(max_length=100, default=False)
    area = models.CharField(max_length=100, default=False)
    z = (
        ('AP', 'Andhra Pradesh'),
        ('AR', 'Arunachal Pradesh'),
        ('AS', 'Assam'),
        ('BR', 'Bihar'),
        ('CG', 'Chhattisgarh'),
        ('GA', 'Goa'),
        ('GJ', 'Gujarat'),
        ('HR', 'Haryana'),
        ('HP', 'Himachal Pradesh'),
        ('JK', 'Jammu and Kashmir'),
        ('JH', 'Jharkhand'),
        ('KA', 'Karnataka'),
        ('KL', 'Kerala'),
        ('MP', 'Madhya Pradesh'),
        ('MH', 'Maharashtra'),
        ('MN', 'Manipur'),
        ('ML', 'Meghalaya'),
        ('MZ', 'Mizoram'),
        ('NL', 'Nagaland'),
        ('OD', 'Odisha'),
        ('PB', 'Punjab'),
        ('SK', 'Sikkim'),
        ('TN', 'Tamil Nadu'),
        ('TS', 'Telangana'),
        ('TR', 'Tripura'),
        ('UK', 'Uttrakhand'),
        ('UP', 'Uttar Pradesh'),
        ('WB', 'West Bengal'),
        ('AN', 'Andaman and Nicobar Islands'),
        ('CH', 'Chandigarh'),
        ('DN', 'Dadra and Nagar Haveli'),
        ('DD', 'Daman and Diu'),
        ('DL', 'Delhi'),
        ('LH', 'Ladakh'),
    )

    state = types = models.CharField(max_length=25, choices=z,
                                     null=False, default=False)
    zipcode = models.IntegerField(default=False)
    description = models.TextField(blank=True, default=False)
    price = models.IntegerField(default=False)
    bedrooms = models.IntegerField(default=False)
    latitude = models.FloatField(default='32.1111')
    longitude = models.FloatField(default='32.1111')
    bathrooms = models.IntegerField(default=False)
    sqft = models.IntegerField(default=False)

    date_published = models.DateTimeField(
        auto_now_add=True, verbose_name="date published")
    date_updated = models.DateTimeField(
        auto_now=True, verbose_name="date updated")
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)
    year_built = models.IntegerField(default=0)
    x = (
        ('R', 'Rent'),
        ('S', 'Sell'),
        ('B', 'Both')
    )
    types = models.CharField(max_length=1, choices=x,
                             null=False, default='R')

    y = (
        ('Y', 'yes'),
        ('N', 'No')
    )
    premium = models.CharField(max_length=1, choices=y,
                               null=False, default='N')

    pool = models.BooleanField()

    parking = models.BooleanField()

    gym = models.BooleanField()

    balcony = models.BooleanField()
    z = (
        ('A', 'Apartment'),
        ('H', 'House')
    )
    stay = models.CharField(max_length=1, choices=z,
                            null=False, default='H')

    k = (
        ('V', 'Verified'),
        ('N', 'Not Verified'),
        ('R', 'rejected')
    )
    Verify = models.CharField(max_length=1, choices=k,
                              null=False, default='N')

    def __str__(self):
        return self.title


@receiver(post_delete, sender=PropertyListing)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)


def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(
            instance.owner.username + "-" + instance.title)


pre_save.connect(pre_save_blog_post_receiver, sender=PropertyListing)

property/forms.py
from django import forms

from property.models import PropertyListing


class CreatePropertyListingForm(forms.ModelForm):

    class Meta:
        model = PropertyListing
        fields = ['title', 'body', 'image', 'price', 'image2', 'image3', 'image4',
                  'address', 'city', 'area', 'state', 'zipcode', 'bathrooms', 'bedrooms', 'sqft', 'types',
                  'stay', 'pool', 'balcony', 'gym', 'parking', 'latitude', 'longitude', 'year_built']


class UpdatePropertyListingForm(forms.ModelForm):

    class Meta:
        model = PropertyListing
        fields = ['title', 'body', 'image', 'image2', 'image3', 'price',
                  'address', 'city', 'area', 'state', 'zipcode', 'bathrooms', 'bedrooms', 'sqft',
                  'stay', 'pool', 'balcony', 'gym', 'parking', 'latitude', 'longitude', 'year_built']

    def save(self, commit=True):
        property_listings = self.instance
        property_listings.title = self.cleaned_data['title']
        property_listings.body = self.cleaned_data['body']
        property_listings.address = self.cleaned_data['address']
        property_listings.city = self.cleaned_data['city']
        property_listings.area = self.cleaned_data['area']
        property_listings.state = self.cleaned_data['state']
        property_listings.zipcode = self.cleaned_data['zipcode']
        property_listings.price = self.cleaned_data['price']
        property_listings.bedrooms = self.cleaned_data['bedrooms']
        property_listings.bathrooms = self.cleaned_data['bathrooms']
        property_listings.sqft = self.cleaned_data['sqft']
        property_listings.types = self.cleaned_data['types']
        property_listings.pool = self.cleaned_data['pool']
        property_listings.gym = self.cleaned_data['gym']
        property_listings.parking = self.cleaned_data['parking']
        property_listings.balcony = self.cleaned_data['balcony']
        property_listings.latitude = self.cleaned_data['latitude']
        property_listings.longitude = self.cleaned_data['longitude']
        property_listings.stay = self.cleaned_data['stay']
        property_listings.year_built = self.cleaned_data['year_built']

        if self.cleaned_data['image']:
            property_listings.image = self.cleaned_data['image']

        if self.cleaned_data['image2']:
            property_listings.image = self.cleaned_data['image2']

        if self.cleaned_data['image3']:
            property_listings.image = self.cleaned_data['image3']

        if commit:
            property_listings.save()
        return property_listings

property/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.views import APIView
from blog.models import UserProfile, BankApi
from property.models import PropertyListing
from property.api.serializers import PropertyListingSerializer, AreaPriceSerializer, BankApiSerializer
from django.contrib.auth.models import User
from django_filters import rest_framework as filters
from django_filters.rest_framework import DjangoFilterBackend
import numpy as np


@api_view(['GET', ])
@permission_classes((IsAuthenticated,))
def api_detail_view(request, slug):

    try:
        property_listing = PropertyListing.objects.get(slug=slug)

    except PropertyListing.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    serializer = PropertyListingSerializer(property_listing)

    return Response(serializer.data)


@api_view(['PUT', ])
@permission_classes((IsAuthenticated,))
def api_update_property_view(request, slug):

    try:
        property_listing = PropertyListing.objects.get(slug=slug)

    except PropertyListing.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    user = request.user
    if PropertyListing.owner != user:
        return Response({'response': "You dont have enough permissions for that"})

    serializer = PropertyListingSerializer(property_listing, data=request.data)
    data = {}
    if serializer.is_valid():
        serializer.save()
        data["success"] = "updated success"
        return Response(data=data)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST', ])
@permission_classes((IsAuthenticated,))
def api_delete_property_view(request, slug):

    try:
        property_listing = PropertyListing.objects.get(slug=slug)

    except PropertyListing.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    user = request.user
    if PropertyListing.owner != user:
        return Response({'response': "You dont have enough permissions for that"})

    operation = property_listing.delete()
    data = {}
    if operation:
        data["success"] = "deleted success"
    else:
        data["faliure"] = "failed"
    return Response(data=data)


@api_view(['POST', ])
@permission_classes((IsAuthenticated,))
def api_create_property_view(request):

    account = request.user
    property_listing = PropertyListing(owner=account)

    serializer = PropertyListingSerializer(property_listing, data=request.data)
    deta = {}
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# class ApiPropertyListView(ListAPIView):
#     queryset = PropertyListing.objects.all()

#     serializer_class = PropertyListingSerializer
#     authentication_classes = (TokenAuthentication,)
#     permission_classes = (IsAuthenticated,)
#     pagination_class = PageNumberPagination
#     filter_backends = [DjangoFilterBackend]
#     filterset_fields = ['city', 'price']


class ApiPropertyListView(ListAPIView):
    queryset = PropertyListing.objects.all()

    serializer_class = PropertyListingSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    pagination_class = PageNumberPagination
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['city', 'price']


class ApiPropertyListView1(ListAPIView):
    queryset = PropertyListing.objects.filter(Verify='N')

    serializer_class = PropertyListingSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    pagination_class = PageNumberPagination
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['city', 'price']


class ApiAreaPriceView(ListAPIView):

    def get(self, request, format=None):
        snippets = PropertyListing.objects.all()
        authentication_classes = (TokenAuthentication,)
        permission_classes = (IsAuthenticated,)
        pagination_class = PageNumberPagination
        filter_backends = [DjangoFilterBackend]
        filterset_fields = ['area', 'price']
        serializer = AreaPriceSerializer(snippets, many=True)
        value = []
        for i in serializer.data:
            value.append(i['price'])
        avg = np.mean(value)
        print(avg)
        return Response(avg)


class ApiBankListView(ListAPIView):

    def get(self, request, format=None):
        snippets = BankApi.objects.all()
        authentication_classes = (TokenAuthentication,)
        permission_classes = (IsAuthenticated,)
        pagination_class = PageNumberPagination
        filter_backends = [DjangoFilterBackend]
        filterset_fields = ['city', 'price']
        serializer = BankApiSerializer(snippets, many=True)
        return Response(serializer.data)


class followview(APIView):

    def post(self, request):

        for each in request.data:

            p1 = request.data[each]['title']
            status1 = request.data[each]['status']

            prop = PropertyListing.objects.get(title=p1)

            if status1 == 'Accepted':

                prop.Verify = 'V'
                prop.save()

            else:

                prop.Verify = 'R'
                prop.save()
                return Response("fknlenl")

property/templates/property/buy_property.html
<h1> You have successfuly purchased the property {{owner}} </h1>

property/templates/property/check_price.html
<h1>Estimated price is = {{ price }}</h1>

property/templates/property/create_property.html
{% extends 'base.html' %}

{% block body %}

<style type="text/css">
	.create-form {
		width: 100%;
		max-width: 100%;
		padding: 15px;
		margin: auto;
	}

	.submit-button {
		max-width: 200px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<!-- <form> -->
			<!-- {{form.as_p}} -->
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required
						autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="5" type="text" name="body" id="id_body"
						placeholder="This property is..." required></textarea>
				</div>

				<!-- Type -->
				<div class="form-group">
					<label for="id_types">For:</label> <select name="types" id="id_types">
						<option value="R">Rent</option>
						<option value="S">Sell</option>
						<option value="B">Both</option>
					</select>
				</div>

				<!-- Stay -->
				<div class="form-group">
					<label for="id_stay">Type:</label> <select name="stay" id="id_stay">
						<option value="A">Apartment</option>
						<option value="H">House</option>
					</select>
				</div>

				<!-- Parking -->
				<div class="form-group">
					<label for="id_parking">Parking:</label>
					<input type="checkbox" name="parking" id="id_parking">
				</div>

				<!-- Balcony -->
				<div class="form-group">
					<label for="id_balcony">Balcony:</label>
					<input type="checkbox" name="balcony" id="id_balcony">
				</div>

				<!-- Gym -->
				<div class="form-group">
					<label for="id_gym">Gym:</label>
					<input type="checkbox" name="gym" id="id_gym">
				</div>

				<!-- Pool -->
				<div class="form-group">
					<label for="id_pool">Pool:</label>
					<input type="checkbox" name="pool" id="id_pool">
				</div>

				<div class="form-group"><label for="id_year_built">Year built:</label> <input type="number"
						name="year_built" value="0" required="" id="id_year_built"></div>

				<!-- Address -->
				<div class="form-group">
					<label for="id_address">Address</label>
					<input class="form-control" type="text" name="address" id="id_address" placeholder="Landmark"
						required>
				</div>

				<!-- City -->
				<div class="form-group">
					<label for="id_city">City</label>
					<input class="form-control" type="text" name="city" id="id_city" required>
				</div>

				<!-- Area -->
				<div class="form-group">
					<label for="id_area">Area</label>
					<input class="form-control" type="text" name="area" id="id_area" required>
				</div>

				<!-- State -->
				<div class="form-group"><label for="id_state">State:</label> <select name="state" id="id_state">
						<option value="AP">Andhra Pradesh</option>

						<option value="AR">Arunachal Pradesh</option>

						<option value="AS">Assam</option>

						<option value="BR">Bihar</option>

						<option value="CG">Chhattisgarh</option>

						<option value="GA">Goa</option>

						<option value="GJ">Gujarat</option>

						<option value="HR">Haryana</option>

						<option value="HP">Himachal Pradesh</option>

						<option value="JK">Jammu and Kashmir</option>

						<option value="JH">Jharkhand</option>

						<option value="KA">Karnataka</option>

						<option value="KL">Kerala</option>

						<option value="MP">Madhya Pradesh</option>

						<option value="MH">Maharashtra</option>

						<option value="MN">Manipur</option>

						<option value="ML">Meghalaya</option>

						<option value="MZ">Mizoram</option>

						<option value="NL">Nagaland</option>

						<option value="OD">Odisha</option>

						<option value="PB">Punjab</option>

						<option value="SK">Sikkim</option>

						<option value="TN">Tamil Nadu</option>

						<option value="TS">Telangana</option>

						<option value="TR">Tripura</option>

						<option value="UK">Uttrakhand</option>

						<option value="UP">Uttar Pradesh</option>

						<option value="WB">West Bengal</option>

						<option value="AN">Andaman and Nicobar Islands</option>

						<option value="CH">Chandigarh</option>

						<option value="DN">Dadra and Nagar Haveli</option>

						<option value="DD">Daman and Diu</option>

						<option value="DL">Delhi</option>

						<option value="LH">Ladakh</option>

					</select></div>

				<!-- Zipcode -->
				<div class="form-group">
					<label for="id_zipcode">Zipcode</label>
					<input class="form-control" type="text" name="zipcode" id="id_zipcode" required>
				</div>

				<!-- Image -->
				<div class="form-group">
					<label for="id_image">Image</label>
					<input type="file" name="image" id="id_image" accept="image/*" required>
				</div>

				<!-- Image2 -->
				<div class="form-group">
					<label for="id_image2">Interior</label>
					<input type="file" name="image2" id="id_image2" accept="image/*">
				</div>

				<!-- Image3 -->
				<div class="form-group">
					<label for="id_image3">Interior</label>
					<input type="file" name="image3" id="id_image3" accept="image/*">
				</div>

				<!-- Image4 -->
				<div class="form-group">
					<label for="id_image4">Floorplan</label>
					<input type="file" name="image4" id="id_image4" accept="image/*">
				</div>

				<!-- Price -->
				<div class="form-group">
					<label for="id_price">Price</label>
					<input class="form-control" type="number" name="price" id="id_price" required>
				</div>

				<!-- Sqft -->
				<div class="form-group">
					<label for="id_sqft">Sq.ft</label>
					<input class="form-control" type="number" name="sqft" id="id_sqft" required>
				</div>

				<!-- Bedrooms -->
				<div class="form-group">
					<label for="id_bedrooms">Bedrooms</label>
					<input class="form-control" type="number" name="bedrooms" id="id_bedrooms" required>
				</div>

				<!-- Bathrooms -->
				<div class="form-group">
					<label for="id_bathrooms">Bathrooms</label>
					<input class="form-control" type="number" name="bathrooms" id="id_bathrooms" required>
				</div>
				<!-- latitude -->
				<div class="form-group">
					<label for="id_latitude">latitude</label>
					<input class="form-control" name="latitude" id="id_latitude" required>
				</div>
				<!-- longitude -->
				<div class="form-group">
					<label for="id_longitude">longitude</label>
					<input class="form-control" name="longitude" id="id_longitude" required>
				</div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>
		</div>
	</div>
</div>

<div id="map_div" style="width:75%;height:500px;margin:90px"></div>
<script>
	// Initialize and add the map
	function initMap() {
		// The location of Uluru
		var add_marker = null, map = null;  //Declare vaiable
		var sricity = { lat: 11.342, lng: 77.728165 };

		// map load
		var map = new google.maps.Map(document.getElementById('map_div'), {
			zoom: 5, center: sricity
		});

		map.addListener("click", function (e) {
			if (add_marker != null) {            //already set marker to clear
				add_marker.setMap(null);
				add_marker = null;
			}

			// Dynamic to set marker based on click event
			add_marker = new google.maps.Marker({
				map: map,
				position: new google.maps.LatLng(e.latLng.lat(), e.latLng.lng()),
				zoom: 10
			});
			document.getElementById('id_latitude').value = e.latLng.lat().toFixed(4)
			document.getElementById('id_longitude').value = e.latLng.lng().toFixed(4)
		});
	}
</script>
<script async defer
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYl3jkGGMzayse2hTeqApY0qanvqXdmaI&callback=initMap">
	</script>

{% endblock %}

property/templates/property/form.html
<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

    <!-- title -->
    <div class="form-group">
        <label for="id_title">Title</label>
        <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
    </div>

    <!-- Body -->
    <div class="form-group">
        <label for="id_body">Content</label>
        <textarea class="form-control" rows="5" type="text" name="body" id="id_body" placeholder="This property is..."
            required></textarea>
    </div>

    <!-- Type -->
    <div class="form-group">
        <p><label for="id_types">Types:</label> <select name="types" id="id_types">
                <option value="R">Rent</option>

                <option value="S">Sell</option>

                <option value="B">Both</option>

            </select></p>
    </div>

    <div class="form-group">
        <p><label for="id_premium">Premium:</label> <select name="premium" id="id_premium">
                <option value="Y">yes</option>

                <option value="N">No</option>

            </select></p>
    </div>


    <!-- Address -->
    <div class="form-group">
        <label for="id_address">Address</label>
        <input class="form-control" type="text" name="address" id="id_address" placeholder="Landmark" required>
    </div>

    <!-- City -->
    <div class="form-group">
        <label for="id_city">City</label>
        <input class="form-control" type="text" name="city" id="id_city" required>
    </div>

    <!-- State -->
    <div class="form-group">
        <label for="id_state">State</label>
        <input class="form-control" type="text" name="state" id="id_state" required>
    </div>

    <!-- Zipcode -->
    <div class="form-group">
        <label for="id_zipcode">Zipcode</label>
        <input class="form-control" type="text" name="zipcode" id="id_zipcode" required>
    </div>

    <!-- Image -->
    <div class="form-group">
        <label for="id_image">Image</label>
        <input type="file" name="image" id="id_image" accept="image/*" required>
    </div>

    <!-- Image2 -->
    <div class="form-group">
        <label for="id_image2">Image2</label>
        <input type="file" name="image2" id="id_image2" accept="image/*">
    </div>

    <!-- Image3 -->
    <div class="form-group">
        <label for="id_image3">Image3</label>
        <input type="file" name="image3" id="id_image3" accept="image/*">
    </div>

    <!-- Price -->
    <div class="form-group">
        <label for="id_price">Price</label>
        <input class="form-control" type="number" name="price" id="id_price" required>
    </div>

    <!-- Sqft -->
    <div class="form-group">
        <label for="id_sqft">Sq.ft</label>
        <input class="form-control" type="number" name="sqft" id="id_sqft" required>
    </div>

    <!-- Bedrooms -->
    <div class="form-group">
        <label for="id_bedrooms">Bedrooms</label>
        <input class="form-control" type="number" name="bedrooms" id="id_bedrooms" required>
    </div>

    <!-- Bathrooms -->
    <div class="form-group">
        <label for="id_bathrooms">Bathrooms</label>
        <input class="form-control" type="number" name="bathrooms" id="id_bathrooms" required>
    </div>