blog/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.home, name='home'),
    path('mapssas/',views.buymaps,name='buymaps'),
    path('account/', views.account_view, name='account'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile_view, name='profile'),
    # path('edit/', views.edit_profile_view, name='edit'),
    path('search/', views.search_view, name='search'),
    path('rent/', views.rent_view, name='rent'),
    path('sell/', views.sell_view, name='sell'),
    path('type1/', views.type1_view, name='type1'),
    path('type2/', views.type2_view, name='type2'),
    path('search_s/', views.sell_search_view, name='search_s'),
    path('search_r/', views.rent_search_view, name='search_r'),
    path('search_t1/', views.t1_search_view, name='search_t1'),
    path('search_t2/', views.t2_search_view, name='search_t2'),
    path('<city>/', views.city_view, name='city'),
    path('<city>/list', views.city_props, name='props'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         views.activate, name='activate'),
    path('profile/', views.profile_view, name='profile')      
]

mysite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from blog.views import (
    must_authenticate_view
)

urlpatterns = [
    path('property/', include('property.urls')),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('must_authenticate/', must_authenticate_view,
         name="must_authenticate"),

    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payments/', include('payments.urls')),
    # rest_framework
    path('api/property/', include('property.api.urls', 'property_api')),
    path('api/account/', include('blog.api.urls', 'blog_api'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

payments/urls.py
from django.urls import path
from payments.views import(
    buy_property_view,
    payment_done,
    payment_canceled,
    make_property_premium,
    blockchain_ledger,
    invoice
)

app_name = "payments"

urlpatterns = [
    path('invoices/<slug>/', invoice, name="invoices"),
    path('blockchain/', blockchain_ledger, name="ledger"),
    path('<slug>/buy', buy_property_view, name="buy"),
    path('<slug>/premium/', make_property_premium, name='premium'),
    path('done/<slug>/', payment_done, name="done"),
    path('canceled/', payment_canceled, name="canceled"),
]

property/urls.py
from django.urls import path
from property.views import(
    create_property_view,
    detail_property_view,
    edit_property_view,
    check_price,
    bank_api
)

app_name = 'property'

urlpatterns = [
    path('create/', create_property_view, name="create"),
    path('<slug>/', detail_property_view, name="detail"),
    path('<slug>/price', check_price, name="price"),
    path('<slug>/edit', edit_property_view, name="edit"),
    path('<slug>/bank', bank_api, name="bank"),

]

payments/models.py
from django.db import models

# Create your models here.

payments/views.py
import hashlib
import datetime

from django.shortcuts import render, redirect, get_object_or_404
from property.models import PropertyListing
from property.forms import CreatePropertyListingForm, UpdatePropertyListingForm
from blog.models import UserProfile
from django.contrib.auth.models import User

from django.urls import reverse
from django.shortcuts import render
from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt

from datetime import datetime
import random
# Create your views here.
from blog.models import Invoice

from django.http import HttpResponse
from django.views.generic import View
from django.template.loader import get_template
from .utils import render_to_pdf
from django.core.files.base import ContentFile
from django.utils.text import slugify


invoices = Invoice.objects.all()
length = len(invoices)
# print(invoices)
# print(length)


class Block:
    blockNo = 0
    data = None
    next = None
    hash = None
    nonce = 0
    previous_hash = 0x0
    timestamp = datetime.now()

    def __init__(self, data):
        self.data = data

    def hash(self):
        h = hashlib.sha256()
        h.update(
            str(self.nonce).encode('utf-8') +
            str(self.data).encode('utf-8')
        )
        return h.hexdigest()

    def __str__(self):
        return "Block_Hash: " + str(self.hash()) + "\nBlockNo: " + str(self.blockNo) + "\nBlock Data: " + str(self.data) + "\nHashes: " + str(self.nonce) + "\n"


class Blockchain:

    diff = 1
    maxNonce = 2**32
    target = 2 ** (256-diff)

    block = Block("Genesis")
    dummy = head = block

    def add(self, block):

        block.previous_hash = self.block.hash()
        block.blockNo = self.block.blockNo + 1

        self.block.next = block
        self.block = self.block.next

    def mine(self, block):
        for n in range(self.maxNonce):
            if int(block.hash(), 16) <= self.target:
                self.add(block)
                return(block)
                break
            else:
                block.nonce += 1


blockchain = Blockchain()


@csrf_exempt
def payment_done(request, slug, *args, **kwargs):
    context = {}
    user = request.user
    property_listings = get_object_or_404(PropertyListing, slug=slug)
    previous_owner = property_listings.owner
    property_listings.owner = user
    property_listings.save()
    print("Printing list", property_listings.price)
    context = {
        'date': datetime.date(datetime.now()),
        'property': property_listings,
        'user': user,
        'registery': property_listings.price*0.1,
        'tax': property_listings.price*0.01,
        'final': property_listings.price*1.11,
        'invoice_id': random.randint(10000, 99999)
    }
    obj = Invoice(issued_to=user, property_purchased=property_listings, date=datetime.date(datetime.now()),
                  registery=property_listings.price*.1, tax=property_listings.price*.01, final=property_listings.price*1.11, invoice_id=random.randint(10000, 99999),
                  slug=slugify(user.username + "-" + property_listings.title))
    obj.save()

    return render(request, 'done.html', context)


def blockchain_ledger(request):

    context = {}
    ledger = [0]*length
    print(invoices)
    for i in range(length):
        ledger[i] = blockchain.mine(Block(invoices[i]))

    while blockchain.head != None:
        blockchain.head = blockchain.head.next

    context['ledger'] = ledger
    return render(request, 'blockchain_ledger.html', context)


@csrf_exempt
def payment_canceled(request):
    return render(request, 'canceled.html')


def buy_property_view(request, slug):
    context = {}

    user = request.user
    property_listings = get_object_or_404(PropertyListing, slug=slug)
    paypal_dict = {
        "business": "hyp6773@gmail.com",
        "amount": property_listings.price,
        "item_name": property_listings.title,
        "invoice": property_listings.title,
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('payments:done', kwargs={'slug': property_listings.slug})),
        "cancel_return": request.build_absolute_uri(reverse('payments:canceled')),
    }
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form}
    return render(request, "payments.html", context)


def make_property_premium(request, slug):
    context = {}
    user = request.user
    property_listings = get_object_or_404(PropertyListing, slug=slug)

    paypal_dict = {
        "business": "hyp6773@gmail.com",
        "amount": property_listings.price,
        "item_name": property_listings.title,
        "invoice": property_listings.title,
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('payments:done', kwargs={'slug': property_listings.slug})),
        "cancel_return": request.build_absolute_uri(reverse('payments:canceled')),
    }

    property_listings.premium = "Y"
    property_listings.save()

    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form}
    return render(request, "premium.html", context)


def invoice(request, slug):
    context = {}
    invoices = get_object_or_404(Invoice, slug=slug)
    context = {
        'date': invoices.date,
        'property': invoices.property_purchased,
        'user': invoices.issued_to,
        'registery': invoices.registery,
        'final': invoices.final,
        'invoice_id': invoices.invoice_id
    }
    return render(request, 'done.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Reals</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'assets/images/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" type="{% static 'text/css" href= "assets/css/responsive.css' %}">
    <link rel="stylesheet" type="{% static 'text/css" href= "assets/css/color.css' %}">
</head>

<body>
    <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->


    <div class="">

        <header>

            <div class="top-header">
                <div class="container">
                    <div class="row justify-content-between">
                        <div class="col-xl-6 col-md-7 col-sm-12">
                            <div class="header-address">
                                <a href="#">
                                    <i class="la la-phone-square"></i>
                                    <span>+91 987654321</span>
                                </a>
                                <a href="#">
                                    <i class="la la-map-marker"></i>
                                    <span>FLM Mall, Hydderabad, TS</span>
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-3 col-md-5 col-sm-12">
                            <div class="header-social">
                                <a href="#">
                                    <i class="fa fa-facebook"></i>
                                </a>
                                <a href="#">
                                    <i class="fa fa-twitter"></i>
                                </a>
                                <a href="#">
                                    <i class="fa fa-instagram"></i>
                                </a>
                                <a href="#">
                                    <i class="fa fa-linkedin"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="header">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <nav class="navbar navbar-expand-lg navbar-light">
                                <a class="navbar-brand" href="{% url 'blog:home' %}">
                                    <img src="static/assets/images/logo - Copy.png" alt="">
                                </a>
                                <button class="menu-button" type="button" data-toggle="collapse"
                                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent">
                                    <span class="icon-spar"></span>
                                    <span class="icon-spar"></span>
                                    <span class="icon-spar"></span>
                                </button>

                                <div class="navbar-collapse" id="navbarSupportedContent">
                                    <ul class="navbar-nav mr-auto">
                                        <li class="nav-item dropdown active">

                                            <div class="dropdown-menu animated">

                                            </div>
                                        </li>
                                        <li class="nav-item dropdown">

                                            <div class="dropdown-menu animated">

                                            </div>
                                        </li>
                                        <li class="nav-item dropdown">

                                            <div class="dropdown-menu animated">

                                            </div>
                                        </li>
                                        <li class="nav-item dropdown">

                                            <div class="dropdown-menu animated">

                                            </div>
                                        </li>
                                    </ul>
                                    <div class="d-inline my-2 my-lg-0">
                                        {% if request.user.is_authenticated %}
                                        Hi,{{ user.username }}&nbsp;
                                        <a class="p-2 text-dark" href="{% url 'blog:home' %}">Home</a>
                                        <a class="p-2 text-dark" href="{% url 'property:create' %}">Submit a
                                            Property</a>
                                        <a class="p-2 text-dark" href="{% url 'blog:account' %}">Account</a>
                                        <a class="p-2 text-dark" href="{% url 'blog:profile' %}">Profile</a>
                                        <a class="p-2 text-dark" href="{% url 'blog:logout' %}">Logout</a>
                                        {% else %}
                                        <a class="p-2 text-dark" href="{% url 'blog:home' %}">Home</a>
                                        <a class="p-2 text-dark" href="{% url 'blog:login' %}">Login</a>
                                        <a class="btn btn-outline-primary" href="{% url 'blog:signup' %}">Register</a>
                                        {% endif %}
                                    </div>
                                    <a href="#" title="" class="close-menu"><i class="la la-close"></i></a>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

        </header>
        <!--header end-->

        <!-- <div class="popup" id="sign-popup">
            <h3>Sign In to your Account</h3>
            <div class="popup-form">
                <form>
                    <div class="form-field">
                        <input type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-field">
                        <input type="text" name="password" placeholder="Password">
                    </div>
                    <div class="form-cp">
                        <div class="form-field">
                            <div class="input-field">
                                <input type="checkbox" name="ccc" id="cc1">
                                <label for="cc1">
                                    <span></span>
                                    <small>Remember me</small>
                                </label>
                            </div>
                        </div>
                        <a href="#" title="">Forgot Password?</a>
                    </div>

                    <button type="submit" class="btn2">Sign In</button>
                </form>
                <a href="#" title="" class="fb-btn"> <i class="fa fa-facebook"></i>Sign In With Facebook</a>
            </div>
        </div> -->
        <!--popup end-->

        <!-- <div class="popup" id="register-popup">
            <h3>Register</h3>
            <div class="popup-form">
                <form method="POST">
                    <div class="form-field">
                        <input type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-field">
                        <input type="text" name="email" placeholder="Email">
                    </div>
                    <div class="form-field">
                        <input type="text" name="password" placeholder="Password">
                    </div>
                    <div class="form-cp">
                        <div class="form-field">
                            <div class="input-field">
                                <input type="checkbox" name="ccc" id="cc2">
                                <label for="cc2">
                                    <span></span>
                                    <small>I agree with terms</small>
                                </label>
                            </div>
                        </div>
                        <a href="#" title="" class="signin-op">Have an account?</a>
                    </div>

                    <button type="submit" class="btn2">Register</button>
                </form>
            </div>
        </div> -->
        <!--popup end-->

        {% block body %}

        {% endblock %}

        {% block map %}

        {% endblock %}
        <section class="fullwidth-home-map">
            <!-- <h3 class="vis-hid">Visible Heading</h3>
            <div id="map" data-map-zoom="9"></div> -->
            <br>
            <br>
        </section>
        <a href="#" title="">
            <section class="cta section-padding">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="cta-text">
                                <h2>Discover a home you'll love to stay</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </a>

        <section class="bottom section-padding">
            <div class="container">
                <div class="row">
                    <div class="col-xl-4 col-sm-6 col-md-4">
                        <div class="bottom-logo">
                            <img src="assets/images/logo.png" alt="" class="img-fluid">
                        </div>
                    </div>
                    <div class="col-xl-3 col-sm-6 col-md-3">
                        <div class="bottom-list">
                            <h3>Helpful Links</h3>
                            <ul>
                                <li>
                                    <a href="{% url 'blog:home' %}" title="">Home</a>
                                </li>

                            </ul>
                        </div>
                        <!--bottom-list end-->
                    </div>
                    <div class="col-xl-5 col-sm-12 col-md-5 pl-0">
                        <div class="bottom-desc">
                            <h3>Aditional Information</h3>
                            <p>Thank you for visiting our website.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="footer-content">
                            <div class="row justify-content-between">
                                <div class="col-xl-6 col-md-6">
                                    <div class="copyright">
                                        <p>&copy; All Rights Reserved.</p>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-md-6">
                                    <div class="footer-social">
                                        <a href="#">
                                            <i class="fa fa-facebook"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fa fa-linkedin"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!--footer end-->


    </div>
    <!--wrapper end-->






    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/modernizr-3.6.0.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script>

    <!-- Maps -->




</body>

</html>

templates/blockchain_ledger.html
<head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Invoices</th>
                <th scope="col">Block hash</th>
                <th scope="col">Owner</th>
            </tr>
        </thead>
        <tbody>
            {% for ledger in ledger %}
            <tr>
                <th scope="row">1</th>
                <td><a href="{% url 'payments:invoices' ledger.data.slug %}">{{ledger.data}}</a></td>
                <td>{{ledger.hash}}</td>
                <td>{{ledger.data.issued_to}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</head>

templates/payments.html
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}

templates/premium.html
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}

templates/profile.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/new.css' %}">


</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4">REAL</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{% url 'blog:home' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'property:create' %}">submit property</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">

            <a class="nav-item nav-link" href="{% url 'blog:account' %}">account</a>
            <a class="nav-item nav-link" href="{% url 'blog:logout' %}">Logout</a>

            <a class="nav-item nav-link" href="{% url 'blog:login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'blog:signup' %}">Register</a>

          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% load crispy_forms_tags %}
        <div class="content-section">
          <div class="media">
            <img class="rounded-circle account-img" src="https://www.w3schools.com/images/picture.jpg">
            <div class="media-body">
              <h2 class="account-heading">{{ user.username }}</h2>
              <p class="text-secondary">{{ user.email }}</p>
            </div>
          </div>

          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Info</legend>
              {{ u_form|crispy }}
            </fieldset>
            <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
          </form>

        </div>
      </div>

    </div>
  </main>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>